import js from '@eslint/js';
import nextVitals from 'eslint-config-next/core-web-vitals';
import nextTs from 'eslint-config-next/typescript';
import prettier from 'eslint-config-prettier/flat';
import importX from 'eslint-plugin-import-x';
import perfectionist from 'eslint-plugin-perfectionist';
import unusedImports from 'eslint-plugin-unused-imports';
import { defineConfig, globalIgnores } from 'eslint/config';

export default defineConfig([
  js.configs.recommended,
  ...nextVitals,
  ...nextTs,
  {
    plugins: {
      'import-x': importX,
      perfectionist,
      'unused-imports': unusedImports,
    },
    settings: {
      'import-x/resolver': {
        typescript: true,
      },
    },
    rules: {
      'import-x/first': 'error',
      'import-x/exports-last': 'error',
      'import-x/newline-after-import': ['error', { count: 1 }],
      'import-x/no-restricted-paths': [
        'error',
        {
          zones: [
            {
              target: './src/lib',
              from: ['./src/server', './src/features', './src/components', './src/app'],
              message:
                'src/lib must stay framework-neutral: no imports from server, features, components or app.',
            },
            {
              target: './src/components/ui',
              from: ['./src/features', './src/server'],
              message: 'Generic UI primitives must not depend on a feature or on server code.',
            },
            {
              target: './src/features',
              from: './src/app',
              message: 'Feature modules must not import from route files.',
            },
          ],
        },
      ],
      'perfectionist/sort-imports': [
        'error',
        {
          internalPattern: ['@/.*'],
          order: 'asc',
          type: 'natural',
        },
      ],
      'perfectionist/sort-named-imports': 'error',
      'perfectionist/sort-named-exports': 'error',
      'perfectionist/sort-variable-declarations': 'off',
      'sort-vars': ['error', { ignoreCase: false }],
      'no-unused-vars': 'off',
      '@typescript-eslint/no-unused-vars': 'off',
      'unused-imports/no-unused-imports': 'error',
      'unused-imports/no-unused-vars': [
        'warn',
        {
          args: 'after-used',
          argsIgnorePattern: '^_',
          ignoreRestSiblings: true,
          vars: 'all',
          varsIgnorePattern: '^_',
        },
      ],
      'no-debugger': 'error',
      'prefer-const': 'error',
    },
  },
  {
    // Next.js route files co-locate segment config (`export const metadata`,
    // `size`, `contentType`, `dynamic`) with the default export by convention;
    // exports-last cannot be satisfied without fighting the framework.
    files: ['src/app/**/*.{ts,tsx}'],
    rules: {
      'import-x/exports-last': 'off',
    },
  },
  {
    // Test files and their configs: helpers export setup functions after code,
    // and Playwright's fixture callback parameter is named `use` (not a React hook).
    files: ['tests/**/*.ts', '*.config.ts'],
    rules: {
      'import-x/exports-last': 'off',
      'react-hooks/rules-of-hooks': 'off',
    },
  },
  prettier,
  globalIgnores([
    '.next/**',
    'coverage/**',
    'dist/**',
    'node_modules/**',
    'out/**',
    // Generated by `pnpm db:pull` — not hand-maintained.
    'src/server/db/schema.ts',
    'src/server/db/relations.ts',
  ]),
]);
