import 'server-only';
import { drizzle } from 'drizzle-orm/postgres-js';
import postgres from 'postgres';

import { serverEnv } from '../env';
import * as relations from './relations';
import * as schema from './schema';

/**
 * Server-only database client.
 *
 * The schema in `./schema` and `./relations` is generated by `pnpm db:pull`
 * from the live database (owned in DataGrip) — do not edit those files.
 *
 * `import 'server-only'` makes `next build` fail if this module is pulled into a
 * Client Component. Consumers import from `@/server/db`, never `@/server/db/schema`.
 */

const client = postgres(serverEnv.DATABASE_URL, { prepare: false });

const db = drizzle(client, { schema: { ...schema, ...relations } });

export { db, schema };
